spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${SPRING_MYSQL_URL}:${SPRING_MYSQL_PORT}/ai_code_platform?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ${SPRING_MYSQL_PASSWORD}
  # redis
  data:
    redis:
      username: default
      ttl: 3600
      database: 0
      host: ${SPRING_REDIS_URL}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}
      timeout: 5000
  #RabbitMQ配置
  rabbitmq:
    host: ${RABBITMQ_URL} # 你的虚拟机IP
    port: ${RABBITMQ_PORT} # 端口
    virtual-host: ${RABBITMQ_VIRTUAL_HOST} # 虚拟主机
    username: ${RABBITMQ_USUER_NAME} # 用户名
    password: ${RABBITMQ_PASSWORD} # 密码