spring:
  application:
    name: ai-code-platform
  profiles:
    active: dev
  #session 30 天过期
  session:
    store-type: redis
    timeout: 2592000
  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 8082
  servlet:
    context-path: /api
    #cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ai.codeplatform.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

