spring:
  security:
    #登录配置
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user
            redirect-uri: ${FRONTEND_HOME_PAGE_URL}/api/login/oauth2/code/github
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${SPRING_MYSQL_URL}:${SPRING_MYSQL_PORT}/ai_code_platform?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ${SPRING_MYSQL_PASSWORD}
  # redis
  data:
    redis:
      username: default
      ttl: 3600
      database: 0
      host: ${SPRING_REDIS_URL}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}
      timeout: 5000
# Dubbo
dubbo:
  application:
    qos-enable: false
  registry:
    address: nacos://${NACOS_URL}:${NACOS_PORT:8848}?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 50051
  consumer:
    timeout: 60000
  provider:
    timeout: 60000
cos:
  client:
    host: ${COS_HOST}
    secretId: ${COS_SECRET_ID}
    secretKey: ${COS_SECRET_KEY}
    region: ${COS_REGION}
    bucket: ${COS_BUCKET}
# 生产地址
frontend:
  homePageUrl: ${FRONTEND_HOME_PAGE_URL}
  authUrl: ${FRONTEND_AUTH_URL}
