spring:
  profiles:
    active: dev
  application:
    name: ai-code-app
  # session
  session:
    store-type: redis
    # 30 days expire
    timeout: 2592000
server:
  port: 8125
  servlet:
    context-path: /api
    # 30 days expire
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ai.codeplatform.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
